theme            = "cnl-spirit"
baseurl          = "https://cnl-naturopathie.ch/"

canonifyurls     = true
languageCode     = "fr-fr"
title            = "CNL-Naturopathie"
disableRSS       = true
[params]
    Webmaster          = '<a href="https://jeanmonod.net/">Nicolas Jeanmonod</a>'
    CopyrightHTML      = "© CNL-Naturopathie Lausanne"
