theme            = "cnl-spirit"
baseurl          = "http://cnl-naturopathie.ch/"

canonifyurls     = true
languageCode     = "fr-fr"
title            = "CNL-Naturopathie"
disableRSS       = true
[params]
    Webmaster          = '<a href="mailto:nicolas.jeanmonod@bluewin.ch">Nicolas Jeanmonod</a>'
    CopyrightHTML      = "© CNL-Naturopathie Lausanne"
